-- Import full-plant employee roster from Employee.xlsx
-- Role-preserving: existing codes keep their role (admin/safety); new codes -> user
-- Generated 2026-07-05T12:40:01.270Z
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-115','นางจินตนา ถาวรศิลป์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2741','นายไพบูลย์ เถาว์โท','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3007','น.ส.กนกพร พุฒทอง','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3338','นายปราการณ์ สุริฉาย','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-068','นายนิยม ซองพู','Lean','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-083','นายศุภฤกษ์ กุลราตรี','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-086','นายสุพจน์ ฉ่ำมาลัย','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-188','นายเมธา ชมรุกข์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-235','นายภิญโญ รักษานนท์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-384','นายมงคล กุศล','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-411','นายวิเชียร ศรีโยธา','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-443','นายอภิเดช ฉวิกขุนรัมย์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-544','นายเลิศวิทย์ เริ่มคิดการณ์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-545','นายวีรเดช วงค์กองแก้ว','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-586','นายพงศธร วงษ์มณี','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-654','นายพฤฒิภัค พุ่มพฤกษ์','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-692','นายกฤษณะ ปรินแคน','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-694','นายวันชัย ธรรมวงษี','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-735','นายพินิจพันธ์ เพ่งพินิจ','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-743','นายนพรัตน์ สาธุจรัญ','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-750','นายรัชต์พงษ์ บุญโชติ','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-776','นายกิตติ พันธ์คำเกิด','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-797','นายชัยยุทธ น้อมกลาง','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-812','นายกรินทร์ เครือทอง','Quality Assurance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-131','น.ส.กษมา ภิรมย์ศรี','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-134','น.ส.อรนุช คำลือเมือง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1606','นายธรรมนูญ พงษ์ไธสง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1686','นายคำพันธ์ สาเกตุ','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1776','นายประวิง ไฝ่ไร่','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1839','นายนนทชัย กันกา','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1930','นายวสันต์ จันทคีรี','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2005','นายตรีภพ สมพงษ์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2088','นายยุทธพิชัย สมหวัง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2352','น.ส.สุภาพร ปานพุ่ม','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2446','นายสมเดช สมญา','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2539','นายนิพนธ์ สีระพันธ์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2598','นายถาวร นิลผาพงษ์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2642','น.ส.เกษร อุ่นมุกดา','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2776','น.ส.อารยา เกือกรัมย์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2796','น.ส.พรทิพย์ หอมจันทร์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2847','นายวัฒชัย ปิตตาละตัง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2861','น.ส.การะเกษ สุโพธิ์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2920','น.ส.จิตติมา เปลี่ยนวงษ์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3264','นายประวิท เดชโชค','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3388','นายเสรี สิงห์ชู','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3412','น.ส.บังอร แก้ววิเศษ','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3516','นายอำพล เมฆวัน','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3523','นายณัฐวุฒิ  จันทร์ขำ','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3550','นายวรพันธ์ แฝดสุระ','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3561','น.ส.ปิยมาศ จันเรียน','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3572','น.ส.ดมิสา ศาลางาม','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3578','น.ส.ณัฐธยาน์ สุระชาติ','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3595','นางสาวพินศร  มักคะสุด','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3598','นายอัจฉรา  เปร่งเพิ่มพูล','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-855','นายสำเนียง รุ่งเรือง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-929','นายชัยยุทธิ์ ประสงค์จิรกุล','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-019','นายไสว พลทิแสง','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-027','นายเสถียน ใจกล้า','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-035','นายประทาน นามวงษา','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-040','นายชลธี สุวรรณไตรย์','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-054','นายรังสรรค์ ดุลมา','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-604','นายวาทิศ วินทไชย','Quality Control','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-036','ว่าที่ ร.ต.ธวัชชัย คลังผา','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-317','นายคงกฤช จิตต์หลัง','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-550','นายชลวุธ หมั่นนอก','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-570','นายประพันธ์   ทองพูน','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-571','นายสมยศ เอกจู','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-629','นายทนงค์ ลิมสกุล','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-699','นายอนุวัฒน์ มุกดา','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-700','นายนพพล ตามูล','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-707','นายวสันต์ สาสอน','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-725','นายมนตรี ผอบเพ็ชร','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-726','นายอนันต์ คุ้มทรัพย์','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-737','นายชัยวัฒน์ กลยนี','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-758','นายศตวรรษ วิจิตรวรฉัตร','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-778','นายเพิ่มพล พลอยสุวรรณ์','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-783','นายกิตติธร ทรัพย์ช่วย','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-786','นายอนุวัฒน์ ศรีสุวรรณชัย','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-787','นายภูวดล ดงอนนท์','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-791','นายมณูศักดิ์ คำค้อ','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-792','นายณัฐพงษ์ รูปสิงห์','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-793','นายสุทิน ใสนวน','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-795','นายเพชร ครองชื่น','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-801','นายอภินิชย์ ลุนสิน','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-802','นายชนาพร ทองจิตร','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-804','นายณัฐปกรณ์ แสงทอง','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-805','นายณัฐนันท์ วงศ์เครือศร','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-806','นายถิรวัฒน์ ไชยพันธ์','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-807','นายณัฐพงษ์ สอนนนฐี','Maintenance','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-072','นายดวงชีวิน ประภัสรานันท์','Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-706','นายคมกฤช บุญมา','Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-713','นายสุริยัน เกตุประยูร','Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-213','นายธีระพล หาสจิตโต','PC','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-215','นายอุดม บุญคง','PC','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-216','น.ส.อลิสา สุภวงษ์','PC','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-237','น.ส.สราพร อุทัยศรี','PC','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-084','น.ส.เปรมยุดา สกุลเดียว','PC','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-105','นายวิทยา ภิญโญยิ่ง','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2567','นายสานนท์ พลแสน','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3477','นายสำเริง ลักษร','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3599','นายอภิชัย  นาคำมูล','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3600','นายหงษ์ เนียมชุมแสง','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3601','นายโพธิ์ไทร แก้ววิเชียร','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3602','นายประเสริฐ นาจาน','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-245','น.ส.สุมินตรา ชานนท์','HR','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-252','น.ส.พรพิมล โสตกลาง','HR','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-255','นางจุฑารัตน์ ศรีบุตรา','EHS','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-075','นายชัยทัต บุญเจริญ','EHS','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-065','นายศราวุธ สุทธิบูลย์','Process Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-738','นายสุธีรักษ์ เตยา','Process Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-751','นายบุญฤทธิ์ ชูสนุก','Process Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-798','นายชัยสิทธิ์ ด้วงกัน','Process Engineer','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-186','น.ส.สุพรรณรสา คำยม','Accounting','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-250','น.ส.ลภัสรดา ทองนอก','Accounting','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-253','นางสาวสุกานดา รักษ์ถาวรนันท์','Accounting','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-256','น.ส.พณิดา ศรีชมภู','Accounting','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-074','น.ส.โชติกา ณ ร้อยเอ็ด','Accounting','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-205','น.ส.ปทิตตา พรธาดาศักดิ์','Purchasing','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-235','น.ส.ณภัทร์ พูลสวัสดิ์','Purchasing','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-214','นายศรายุธ พวงผกา','Store','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-234','นายโกสินทร์ ราชประโคน','Store','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2813','น.ส.สุวนันท์ พวงจันทร์','Store','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3525','นายปรนนท์  ชื่นชม','Store','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-133','นายณัฐวุฒิ สุขเนาวรัตน์','IT','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-085','น.ส.ณฐภัทร สุขนิรันดร์กุล','Program','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-246','น.ส.ขนิษฐา แท้รัมย์','Customer Service','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-259','น.ส.มีนตรา วิเชียรพงษ์','Customer Service','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1787','นายสุทิน แสงสุวรรณ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1940','นายเพิน ชูสะติ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2155','นายไพศักดิ์ ม่วงอ่อน','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2363','นายคำนึง เพชรประเสริฐ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2631','นายประยุทธ  ฝากาทอง','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2687','นายโกมิน จันทร์ดี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2734','นายสมพร พุ่มมะลิ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2737','นายชลาธิป จำเรียง','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2851','นายเศรษฐพงศ์ ไพบูลย์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3101','นายสังสรรค์ จันดี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3327','นายเนตร์น้อย พรมหากุล','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3369','นายทิฆัมพร เพสารี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3383','นายทศพร ประภาวิชา','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3414','นายพิชิตชัย พรมจันทร์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3425','นายโกมน อุ่นสวัสดี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3429','นายเจริญทอง ปัญหาไชย','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3430','นายปรัชญา ขาวงาม','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3452','นายอิสระ ดัชถุยาวัตร','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3461','นายสายชล แสงทองไชย์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3475','นายณัฐวัติ ผดุงภักดี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3485','นายใกรญษิต พรมทอง','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3517','นายเกียรติศักดิ์  เรืองเดชา','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3520','นายนิกูลชัย  กองลี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3522','นายวัฒนา  การินทร์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3544','นายปรีชา อสิพงษ์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3568','นายอนันต์ ก่อเกิด','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3570','นายอโนทัย กำเพ็ชร','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3577','นายณัฐสิทธิ์ ผันผาย','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3584','นายธนากร วรรณทวี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3588','นายสุรศักด์  ชมชื่น','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-620','นายนิยม เชื้อหนองทอน','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-895','นายประพันธ์ จันทร์งาม','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-896','นายสมเพชร แสงสุวรรณ์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-088','นายเอกพล วงค์ชนะศรี','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-033','นายพอเจตน์ ใจบุญ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-036','นายสมพร พรประไพ','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-042','นายนิคม ปะเทสังข์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-050','นายสิทธิพล   หมอกมืด','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-060','นายอนุสรณ์ การรัตน์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-329','นายสมนึก กลิ่นรื่น','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1283','น.ส.ณัชชา สุทธิเจริญ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1529','นายสามารถ ครัวจัตุรัส','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1534','น.ส.รัตณาภรณ์ มากเกิด','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1876','นายเรวัต หลาบสุภา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2176','นายโกวิทย์ คำภีร์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2194','นายทวี จิรัมย์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2209','นายดุสิต จำรองพันธ์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2297','นายธนดล สัตบุตร','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2336','นายดำรงค์ฤทธิ์ อินยม','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2404','นายบรรจง สูแพะ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2411','นายณรงค์ศักดิ์  พิมพะ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2429','น.ส.ทองพูน ขุนภักนา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2475','นายวิเศษ เหง้าสุวรรณ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2553','น.ส.เพ็ญนภา มีพิมพ์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2566','น.ส.ประภัสสร ศรีสว่าง','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2612','นายทัศพงษ์ องอาจ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2782','น.ส.วิมล จันทร์สมร','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2818','น.ส.กรชนก กรุดเงิน','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2836','น.ส.ธมลวรรณ ดาวสกุล','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2939','น.ส.สุภาพร คิดกล้า','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2984','น.ส.ขนิษฐา โสคำ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2995','นายสิงห์สังเวียร จำเริญไกร','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3019','น.ส.จันทร์เพ็ญ แสงรส','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3299','นายไพรินทร์ อินทร์ทอง','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3385','นายทักษิณ เพชรโสภา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3419','นายปัญญา ผจญกิจ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3422','น.ส.เทียมจิตร นวลอินทร์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3470','นายธงชัย บุญจิตร','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3474','น.ส.อรณี หมู่ศิริ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3479','นายอลงกรณ์ เทียงดาห์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3503','นายศราวุธ แก้วกิ่ง','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3504','ว่าที่ ร.ต.ธานี วงค์วัฒน์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3508','นายณัฐวัฒน์ พรมสันเทียะ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3529','นายอาทิตย์  ทองปาน','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3530','นายกลองชัย  พันภักดิ์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3539','นายภูริเดช  ขันนาค','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3546','นายวรพล ทองทา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3549','นายอภิวัฒน์ พันธ์เดช','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3573','นายจตุรทนต์ ปิตะธารา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3574','นายศราวุฒิ ทองอ้ม','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3581','นายวิทยา ขันตี','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3590','นายศุภกิจ เหลาเพ็ง','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3594','นางพัชรินทร์  สุขพรรณ์','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3596','นายคมกฤษ  แสนธิ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-761','นายจินดา ไชยพินิจ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-087','นายชานนท์ แสงสุข','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-041','นายสุทิน จันทร์ดี','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-043','นายสุวัลลภ ก้าวธรรม','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-053','นายภูเบศร์ เรือนไทย','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-061','นายวิสันต์ กันนุฬา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-063','นายมนูน อินทร์โสภา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-064','นายบุญเลิศ สุขสมัย','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1195','น.ส.สุดาภร สุดใจ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1372','นายวิชัย เจริญเขต','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1567','นายภาศุ สงค์พิมพ์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2033','นายเอกชัย ประดิษฐ์เทา','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2136','นายทองพูน เพิ่มพูล','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2623','น.ส.หยาดพิรุณ สัตถาผล','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2722','นายณรงค์ ปาติตัง','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2809','น.ส.อรชา ทาสีคำ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2972','น.ส.ทัศดี เวียงแก้ว','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3045','น.ส.นุจรินทร์ เรืองจันทา','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3093','นายวิรัช แจ่มจำรัส','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3105','นายสุขกมล กาภูคำ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3114','นายคชา กล้าหาญ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3169','นายสมพงษ์ ลองพล','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3295','นายชวภณ เสียงเย็น','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3330','นายธีรพงษ์ สิงห์สำราญ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3362','นายสุรสิทธิ์ นรสาร','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3394','นายวีระยุทธ งามดี','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3442','นางประภาภรณ์ อรุณโรจน์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3453','นายประจญ ชะตารัมย์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3455','นายชัชชัย ชนะชัย','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3495','นายพรประชา ไชยลาด','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3500','นายอัตพล โผภูเขียว','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3528','นายสามารถ  สำราญใจ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3533','นายคมสัน เทียนชัย','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3538','นายพนมพร  สมพร','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3557','นายพุฒิพงศ์ ภูษี','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3559','นายธนากร สีหานาม','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3565','นายมงคล เวนุอาธร','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3567','นายพัชกฤตย์ ขันศิลา','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3571','นายชนกันต์ ผลมีศักดิ์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3576','นายนิพนธ์ ชาญเดช','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3586','นายธวัชชัย พิลาพอง','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3587','นายเอกรินทร์ ปัสสาคำ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3597','นายอนุสรณ์  ขุนจร','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-913','นายอรุณ อินผ่อง','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-044','นายสมยศ แดงสูงเนิน','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-047','นายกำปั่น เจือจาน','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-051','นายฐิติศักดิ์ ปรางมาศ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-055','นายวีรศักดิ์ สัตนาโค','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-056','นายสุรชัย เจริญจิตต์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-065','นายสัมฤทธิ์ ตอรัมย์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-069','น.ส.อทิตยา ศรสิทธิ์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-334','นายบัณฑิต ศรีสงคราม','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-368','นายวันชัย จันทร์สว่าง','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-644','นายชัชวาลย์  เชื้อกลางใหญ่','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('G-260','น.ส.เพชรลดา พรมมา','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1058','นายสรศักดิ์ สุริยะ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1101','นายเดชา คำพิมูล','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1598','นายสัญญา คิดโสดา','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1763','นายสมชาย พรมชาติ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1827','นายสุทิศ ภูถมดี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1879','นายวิฑูรย์ สุขเลิศ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-1928','นายกันยา สวนธิ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2101','นายนพรัตน์ พวงพันธ์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2480','นายสมคิด ทรทึก','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2488','นายสราวุฒิ ปานทอง','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2499','นายทรงศักดิ์ สืบเสระ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2634','นายภูณัทกิจ อ่อนวิมล','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2658','น.ส.มาลิณี จอดพิมาย','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2659','นายณรงค์ จอดพิมาย','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2677','นายชาคริต บุญศิริกร','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2929','นายสุวรรณ สุขสถิตย์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-2935','นายพิสิษฐ์ อิ่มเพ็ง','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3012','นายจีราวัฒน์ บวรเกษมพงศ์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3015','นายวิรุต การุณรัตน์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3035','นายจักรินทร์ นิสสัยดี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3062','นายอภิวัฒน์ หาดจันทร์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3096','นายบรรหาญ แสงอ่อน','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3374','นายปัญญา ประวันนา','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3377','นายธนภัทร์ หนุนโชค','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3378','นายจักรพันธ์ เทียนหอม','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3431','นายกฤษณ์ ซื้อจริง','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3501','นายสุภัค โจนรัมย์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3527','นายเกียรติศักดิ์  หล้ามณี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3582','นายกิตติภพ บัวองค์','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3583','นายวัฒนา  สอนไชย','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3591','นายณัฐพงษ์ สีสันงาม','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-603','นายรุ่งโรจน์ วรรณสุทธะ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-057','นายมนตรี ปานเจริญ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-038','นายณรงค์ งิ้วเขียว','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-046','นายสมศักดิ์ เครือลัดดา','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-057','นายวิภาวัส จันทะคาม','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-059','นายเกรียงไกร โพธิ์ศรี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-067','นายจำเนียร ทาเทพ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-204','นายวิรัตน์ หวังชอบ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-441','นายธนาศักดิ์ สุกระวัน','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST189','นายเกียรติศักดิ์  แก้วประทุม','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST596','นางสาววิภาดา  ชัยสีหา','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST621','นายเอกลักษณ์  พงษ์ธนู','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST630','นายสะอาด  นาบำรุง','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST640','นายอัษฎาวุธ  ราศรี','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST650','นายบุรัญ  หาริวงค์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3606','นายอภิสิทธิ์  ป้องศรี','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST654','นายอดิศักดิ์  แสงขาว','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST658','นายลิขิต  สถิตชัย','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST661','นายประเวท  กิ่งพุ่ม','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST664','นายวีรพล  บัวงาม','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3607','นายอนุชิต  อินทมาตย์','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST666','นายภคินัย  สาผม','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST667','นายณัฐพงษ์  ไผ่เรือง','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST684','นายชโนทัย สุขสมบัติ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST694','นายพงษ์สวัสดิ์  ชะนะเคน','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST702','นายธีรพัฒน์  อินทร์สีดา','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST704','นายธีรพงศ์ ทำเจริญตระกูล','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST707','นายกิจชนะ  ยันรัมย์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST708','นายวชิระ ศรีนอก','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST709','นายวัชรินทร์ ยอดดี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST711','นายกิตติพงษ์ นุชเฉย','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST717','นางสาวนฤมล ดีเกตุ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST742','นางสาวจีรนันท์ ลดาพัน','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST743','นายพัฒนกร ศิริเวช','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST745','นายธีรศักดิ์ สุขไชยสงค์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST746','นายเสฏฐพงศ์ กอมาตย์','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST747','นายวิชญ์พล ภูกระบิล','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST748','นายสมหมาย สุขแสวง','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST749','นางสาวอรัญญา อินศวร','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST750','นายกิตติศักดิ์ บูรณะ','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST751','นายฉัตรชัย เชียงริน','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST752','นายพิษณุ พิมมะทา','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST753','นายทวีวัฒน์ นักบุญ','VSM3','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST755','นายอำนาจ ดำรงกิจ','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST756','นายสมพล ทองสุด','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST759','นายเอกชัย โก้พิมาย','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST760','นายชัยยงค์ มณีใส','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST761','นายธีรวัฒน์ อ้นป้อม','Warehouse','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST762','นายธวัชชัย กองเพชร','VSM1','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST763','นายถิรธรรม ทองพา','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST765','น.ส.สุภาศิลป์ ชาคาน','VSM2','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('00','Mr.Ivan Klimov','EHS','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3603','นายวีรพล  บัวงาม','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3604','นายณัฐพงษ์  ไผ่เรือง','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3605','น.ส.นฤมล ดีเกตุ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-814','นายพรชัย ครองใจ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-815','นายวิภาวัส จันทะคาม','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3608','นายประเวท  กิ่งพุ่ม','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3609','นายภคินัย  สาผม','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3610','นายวัชรินทร์ คำศรี','VSM4','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('L-3611','นายธีรพัฒน์  อินทร์สีดา','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-813','น.ส.ศันสนีย์ ดวงจินดา','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('S-070','นายถาวร นิลผาพงษ์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('M-089','นายสัญญา ทองนอก','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-808','นายกิติพันธ์ ดุลแสง','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('T-809','นายอนุชา อุ้มหอบ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST767','นายกล้าณรงค์ ภูบังดาว','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST768','นายพันธกานต์ วงษ์พยัคฆ์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST771','นายประเสริฐศักดิ์ สมบัติ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST773','นายสุรพงศ์ คำดี','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST774','นายทัศนพล หงส์ชุม','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST776','นายเกียรติศักดิ์ ทองยิ่ง','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST779','นายเจตนิพัทธ์ ชมพู','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST780','นายวัชรพล แอมรัมย์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST782','นายพายุ กุลอัก','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST784','นายวินัฐ สิงห์ลี','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST786','นางสาวอังควิภา จามะรีย์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST789','นายภานุพงษ์ การงาน','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST791','นายคธาวุธ กล่ำเชย','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST794','นายพุฒิพงษ์ ฝากเมีย','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST796','นายศุภวิชญ์ แก้วพิลา','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST797','นายพงษ์พิสุทธิ์ ยิ่งสำราญ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST798','นายณัฐพงษ์ ศรีปราชญ์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST799','นายรภีพัฒน์ ขุมเงิน','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST800','นายปฏิพล แกมชัยภูมิ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST801','นายปราโมทย์ อินธิไชย','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST802','นายวรรณชัย โพธิ์หล้า','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST804','นายณัฐพล บัวลี','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST805','นางสาววิมลพรรณ เพชรสังหาร','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST807','นายจักรพันธ์ แก่นจันทร์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST808','นายนาทนิรันดร์ จำปาแก้ว','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST810','นายเจษฎา กาบแก้ว','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST811','นายวัชรินทร์ สุขบรรณ์','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST812','นายภูวดล พริ้งเพราะ','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
INSERT INTO employees (id,name,vsm,role,active) VALUES ('PST814','นายสุชิน อินธิราช','','user',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name, vsm=excluded.vsm, active=1;
